### PR TITLE
chore: update axoproject and use changelog api

### LINKED ISSUE #262: Use parse_changelog::Release::title_no_link
Extending https://github.com/taiki-e/parse-changelog/issues/32.

For example, https://github.com/github-changelog-generator/github-changelog-generator generates headings in the following format:

```markdown
## [v1.0.0-beta.55](https://github.com/ignisda/ryot/tree/v1.0.0-beta.55) (2023-06-05)

[Full Changelog](https://github.com/ignisda/ryot/compare/v1.0.0-beta.54...v1.0.0-beta.55)

**Closed issues:**

- Error: Failed to read source file. [\#116](https://github.com/IgnisDa/ryot/issues/116)
```

But cargo-dist generates the announcement title as follows:
image

I want it to be like `v1.0.0-beta.55 (2023-06-05)`.

### PR DESCRIPTION
**Pull request by Gankra**
fixes #262

### CODE REVIEW

**Comment by Gankra** [comment]
depends on https://github.com/axodotdev/axoproject/pull/37

**Comment by Gankra** [comment]
DO NOT MERGE UNTIL AXOPROJECT RELEASE

**Comment by mistydemeo** [comment]
Mark as draft so we block the ability to merge it before that?

**Comment by mistydemeo** [comment]
axoproject 0.4.7 is out now.

**Review by mistydemeo — APPROVED** [review]

**Pull request merged**
