### PR TITLE
Distinguish "cargo metadata failed" from "cargo is not installed"

### LINKED ISSUE #1500: "cargo metadata" returned non-zero exit code != "cargo" is not installed
As of e7ed7b5e34e6ea9b7754832ed017f4deb1a84275 at least, that error conflates both:

```
Run dist host --steps=check --output-format=json > plan-dist-manifest.json
  × We encountered an issue trying to read your workspace
  ╰─▶   × Your app has a Cargo.toml, but you don't appear to have cargo installed.
        help: Is cargo in your PATH? You can install cargo via: https://rustup.rs/
```

When really what happened was something like this:

```
hi on  main [!] via 🦀 v1.82.0
❯ cargo metadata
error: expected `.`, `=`
 --> Cargo.toml:1:8
  |
1 | package]
  |        ^
  |

hi on  main [!] via 🦀 v1.82.0
❯ echo $?
101
```

On a call with @ashleygwilliams, we agreed I'd contribute a quick fix, the plan is to:

  * Run the command as usual
  * If it failed, check if we think `cargo` is in path (we can use [which](https://lib.rs/crates/which))
    * If it's not, go for the "cargo needs to be installed" error
    * If it is installed, show cargo metadata stdout/stderr to explain why it failed

The unintuitive ordering here is just in case `which` ends up being stricter than the system and it doesn't "see" cargo in PATH when actually just _trying to execute cargo_ would work.

### PR DESCRIPTION
**Pull request by fasterthanlime**
Closes #1500

### CODE REVIEW

**Comment by fasterthanlime** [comment]
in action:

CleanShot 2024-10-29 at 16 31 45@2x

**Comment by fasterthanlime** [comment]
(note: this was a regression introduced recently, which was trying (and succeeding, tbh!) in improving this error message:

CleanShot 2024-10-29 at 16 32 52@2x

)

**Review by duckinator — APPROVED** [review]
Works locally and the implementation is about as simple as it gets. Looks good to me. :+1:

**Review by mistydemeo — APPROVED** [review]
Looks good, seems like a good heuristic!

**Pull request merged**
