### PR TITLE
feat: add create-release config to allow people to draft their own releases

### LINKED ISSUE #366: create way to turn off release creation
https://github.com/libsql/sqld/pull/625/commits/1c652b9daece08082485766227994bbdf72349db

- separate dist plan from release creation
- allow config that doesn't add the create-release job

### PR DESCRIPTION
**Pull request by Gankra**
fixes #366

### CODE REVIEW

**Comment by Gankra** [comment]
Test change: https://github.com/oranda-gallery/cargodisttest/commit/bf613c95e53c997e85c1f97e0742b7bbcc690c3b

Test release: https://github.com/oranda-gallery/cargodisttest/actions/runs/5978340652/job/16220216455

**Comment by Gankra** [comment]
Successful Result: https://github.com/oranda-gallery/cargodisttest/releases/tag/v0.3.58

**Review by ashleygwilliams — APPROVED** [review]
will do docs later, would like a pre-release of this today

**Review by mistydemeo — APPROVED** [review]
Looks good, though I think the suggestion of swapping to `create_release` is a good idea.

**Pull request merged**
