### PR TITLE
Make exe bundle style configurable

### PR DESCRIPTION
**Pull request by localcc**
This solves the issue #125 and allows exe bundle style to be configurable by user.

### CODE REVIEW

**Comment by Gankra** [comment]
I'm afraid this is going to massively conflict with #115, so I'm not gonna be able to review/accept this before that lands. :(

**Comment by niklaswimmer** [comment]
Unfortunately this change seems to break installers, because they are hardcoded to the archive extension (based on the platform). I think we would need to pass the extension into the installer generation as well, and using platform specific values only as a fallback if no extension was explicitly set.

**Comment by localcc** [comment]
I'm not really seeing how this breaks installers as the option is only processed in the executables loop, which has a match clause saying that an installer variant is unreachable

**Comment by niklaswimmer** [comment]
What I meant by this is that the installer script itself won't work (under some circumstances). The script will always try to download a tar archive if it is executed on a Unix host and a zip when on Windows, even if cargo-dist generates zips for all platforms.

**Comment by Gankra** [comment]
yeah I need to finish my refactor which computes way more information centrally and feeds it down to the installers. at that point we can then start spoon-feeding the installers more precise details like per-platform-extensions

**Comment by Gankra** [comment]
The latest commit in #115 now has the WIP refactor of the installers wired up, with a bunch of the end-user configurability disabled (i.e. no more specifying version), as the schema for URLs/paths is in flux and can't yet be guaranteed across versions reliably. The installers now basically just plug together exactly the values fed into them.

However they are missing one large thing that needs to be handled for #111 -- if a package has two binaries defined, that means we'll make a zip with two binaries (whose names won't match the app name or zip name). As such, we need installer.rs to feed down a list of binaries. Similar logic could be used to feed down a map of target-triple => zip-extension/exe-extension, presumably?

**Comment by Gankra** [comment]
sorry about the bad timing of my refactor! gonna close this for now.

**Pull request closed without merging**
