### PR TITLE
feat: add package manager source to library

### PR DESCRIPTION
**Pull request by mistydemeo**
This makes it easier to track which package manager a package comes from for non-Homebrew packages, which could be located in multiple places. I've also added a new method to get a flat list of package name strings from the linkage data.

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
@Gankra and i discussed, want to circle up with @mistydemeo when back from vacation to get this in

**Comment by Gankra** [comment]
Whoops i rebased the wrong PR, don't mind me.

**Comment by mistydemeo** [comment]
This passes `cargo test` and `cargo clippy`, so we can get it in any time.

**Comment by ashleygwilliams** [comment]
can we make a call to get this in or close this? it's been open for a while and it'd be good to make a decision on it.

**Review by mistydemeo — COMMENTED** [review]
We don't have a use in mind for this at the moment, but I do think it'd be useful to track. I can get it updated with the recent changes if we agree on getting it in.

**Comment by ashleygwilliams** [comment]
@mistydemeo i think it's a really good idea so the next extra second we have, let's try to get this in!

**Review by ashleygwilliams — APPROVED** [review]

**Pull request merged**
